# Generated by Django 5.0.1 on 2024-01-24 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('permanent', 'permanent')], max_length=10)),
                ('descriptions', models.TextField()),
                ('requirements', models.TextField()),
                ('application_count', models.IntegerField(default=0)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('permanent', 'permanent')], max_length=9)),
                ('featured_job', models.BooleanField(default=False)),
                ('urgently_hiring', models.BooleanField(default=False)),
                ('base_salary', models.FloatField(default=0.0)),
                ('company_logo', models.ImageField(upload_to='company_logo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.category')),
                ('hiring_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
