# Generated by Django 5.0.1 on 2024-01-28 16:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
