# Generated by Django 5.0.1 on 2024-01-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
