# Generated by Django 5.0.1 on 2024-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_category_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='last_date_to_apply',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='base_salary',
            new_name='max_salary',
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.FloatField(default=0.0),
        ),
    ]
