# Generated by Django 5.0.1 on 2024-01-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_last_date_to_apply_job_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
