# Generated by Django 5.0.1 on 2024-02-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ('-updated',), 'verbose_name_plural': 'Testimonials'},
        ),
    ]
