# Generated by Django 5.0.1 on 2024-01-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('job-seeker', 'Job Seeker'), ('employer', 'employer')], default='job-seeker', max_length=10),
        ),
    ]
